# Generated by Django 4.0.4 on 2022-08-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=8)),
                ('message', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='lname',
            field=models.CharField(max_length=30),
        ),
    ]
