# Generated by Django 4.0.4 on 2022-08-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0002_appointment_alter_register_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TextField(max_length=8),
        ),
    ]
