# Generated by Django 4.0.4 on 2022-09-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0003_alter_appointment_address_alter_appointment_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('Profile_pic', models.ImageField(upload_to='')),
                ('Contractor_name', models.CharField(max_length=10)),
                ('contact', models.IntegerField()),
                ('projects', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='address',
            new_name='Uaddress',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='Udate',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='email',
            new_name='Uemail',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='message',
            new_name='Umessage',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='Uname',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='phone',
            new_name='Uphone',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='Utime',
        ),
        migrations.CreateModel(
            name='Interiors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_id', models.IntegerField(default=100)),
                ('Interior_name', models.CharField(max_length=15)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=35)),
                ('projects', models.ImageField(upload_to='')),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interior_app.contractors')),
            ],
        ),
    ]
